import bakedeggs from "../../img/spinach/bakedeggs.jpg";
import garlicnoodles from "../../img/spinach/garlicnoodles.jpg";
import spinachmuffin from "../../img/spinach/spinachmufin.jpg";
import creamedspinach from "../../img/spinach/creamedspinach.jpg";
import palakpanner from "../../img/spinach/palakpanner.jpg";
const recipes = [
  {
    id: 1,
    name: "Baked Eggs with Spinach",
    time: 30,
    servings: 4,
    ingredients: [
      "2 tsp olive oil",
      "1/4 cup diced shallots",
      "1 1/2 lb baby spinach, large stems removed",
      "4 large eggs",
      "Salt and fresh ground pepper",
      "2 tbsp Asiago cheese",
      "baking spray",
    ],
    steps: [
      "Preheat an oven to 400° F",
      "Lightly spray four oven-safe dishes or ramekins with cooking spray.",
      "Heat a large skillet over medium-low heat, add oil, shallots and cook 2-3 minutes",
      "Add spinach, salt and pepper and cook until the spinach wilts, about 2-3 minutes",
      "Mix in Asiago cheese and remove from heat",
      "Divide the wilted spinach among the oven-safe dishes, making a well in the center of each",
      "Break an egg into each dish and season with salt and pepper",
      "Place the ramekins on one or two rimmed baking sheets and bake until the whites are set for about 17 minutes or to your liking",
      "Serve immediately",
    ],
    image: bakedeggs,
  },
  {
    id: 2,
    name: "Garlic and Spinach Noodles",
    time: 30,
    servings: 4,
    ingredients: [
      "1 small onion",
      "6 garlic cloves",
      "Butter for frying",
      "1/2 cup white wine",
      "1 cup chicken",
      "4 Tbsp. anchovy–caper butter",
      "1 cup cream",
      "1 lb. long pasta",
      "1 bag spinach, chopped into strips",
      "Raclette",
      "Anchovy-caper butterCombine ",
      "1/4 bunch (1/4 cup) parsley ",
      " Zest of 1 lemonly chopped",
    ],
    steps: [
      "In a shallow frying pan, sweat the onion and garlic in a knob of the butter",
      "a pinch of salt over low heat until soft, 5 to 7 minutes",
      "Add the wine and reduce by half, about three minutes. Increase the heat and add the stock",
      "When the liquid comes to a boil, add the butter and cream",
      "let reduce until slightly thickened, 3 to 5 minutes",
      "Drain the pasta and toss with the sauce and the spinach",
      "Allow the heat of the noodles to wilt the spinach",
      "Serve with a satisfyingly hefty grating of cheese",
    ],
    image: garlicnoodles,
  },
  {
    id: 3,
    name: "Baby Spinach Muffins",
    time: 50,
    servings: 2,
    ingredients: [
      "1 very ripe large banana",
      "1 medium gala apple, cored and sliced into 4th's",
      "1/4 cup raw honey or 3-5 pitted dates",
      "2 large eggs",
      "2 teaspoons pure vanilla extract",
      "1 to 2 large handfuls baby spinach",
      "1 cup steel cut oats",
      "1/2 teaspoon baking soda",
      "Toppings of choice: granola, choco chips ,dried fruit",
    ],
    steps: [
      " Preheat an oven to 350°F and grease a mini muffin pan with oil or butter, set aside",
      "In order, place all of the ingredients into a high powered blender capable of grinding grain",
      "Wet all the ingredients first",
      "Blend until smooth, about 45 seconds",
      "Fill the mini muffin pan cups 3/4th's full and sprinkle with additional toppings, if desired",
      "Place the muffin tin inside the oven",
      "Bake for 12 minutes and let cool completely before serving",
    ],
    image: spinachmuffin,
  },
  {
    id: 4,
    name: "Spicy Creamed Spinach",
    time: 40,
    servings: 4,
    ingredients: [
      "13.5oz. can full-fat coconut milk",
      "8 oz. fresh spinach",
      "1 yellow onion",
      "2 cloves garlic",
      "1 Tbsp grated fresh ginger",
      "2 Tbsp olive oil",
      "2 tsp ground cumin",
      "1 tsp garam masala",
      "1/2 tsp turmeric",
      "1/4¼ tsp cayenne pepper",
      "1 large tomato",
    ],
    steps: [
      "Add the coconut milk and spinach to a large pot",
      "Stir and cook over medium heat until the coconut milk is warmed through and has wilted the spinach",
      "Remove from the heat as soon as the spinach has wilted to avoid over cooking the spinach",
      "Transfer the warm coconut milk and spinach to a blender and pulse until the spinach is in small pieces. Set this mixture aside",
      "Dice the onion, mince the garlic, and grate the ginger",
      "Add the onion, garlic, and ginger to a large skillet along with the olive oil",
      "Sauté over medium heat until the onions are soft (about 5 minutes)",
      "Add the cumin, garam masala, turmeric, and cayenne to the skillet",
      "Stir and cook the spices with the onion garlic, and ginger for about two minutes more",
      "Dice the tomato and add it to the skillet along with about 1/4 cup water",
      "Stir and cook the tomato with the other ingredients, until the tomato has broken down (5-8 minutes)",
      "Finally, add the coconut and spinach mixture to the skillet and stir to combine",
      "Allow the mixture to heat through, stirring occasionally",
      "Taste the creamed spinach and add salt to taste",
      "Start with 1/4 tsp, adding more as needed until the flavors pop",
    ],
    image: creamedspinach,
  },
  {
    id: 5,
    name: "Palak with Panner",
    time: 40,
    servings: 2,
    ingredients: [
      "14 ounces paneer",
      "pound pre-washed baby spinach",
      "2 tablespoons ghee or sunflower oil",
      "1 medium yellow onion, finely diced (about 1 1/2 cups)",
      "2 tablespoons minced ginger",
      "4 cloves garlic, minced",
      "1 serrano pepper, seeded and finely diced",
      "1 teaspoon cumin seeds",
      "2 teaspoons garam masala",
      "1/4 teaspoon turmeric",
      "1/4 teaspoon cayenne pepper",
      "1/2 cup heavy cream",
      "1 1/4 teaspoon kosher salt",
    ],
    steps: [
      "Pan Fry Paneer",
      "Cut the paneer into small pieces",
      "Slice the block of paneer into about 1/3-inch slices",
      "Take each slice of paneer and cut it into smaller pieces",
      "Heat 1 1/2 tablespoons of ghee or oil in a large skillet over medium heat",
      "Add half of the paneer pieces and pan fry until golden brown, about 2 to 3 minutes",
      "Sprinkle a small pinch of salt over the paneer before flipping them over",
      "Then, pan fry the other side until golden brown, about 2 minutes. Transfer the fried paneer to a plate",
      "Add another 1 1/2 tablespoons of ghee or oil to the skillet and repeat the pan frying step above",
      "Transfer the remaining fried paneer to the plate",
      "Make Spinach Sauce",
      "Fill a large saucepan with about 3 quarts of water and bring it to boil",
      "Add the baby spinach to the boiling water",
      "Once the spinach starts wilting, add the remaining spinach",
      "Cook for about a minute, until all the spinach wilts",
      "Use a spider spatula to remove the spinach from the saucepan or drain the spinach into a colander",
      "Transfer the spinach to a food processor. You don’t need to squeeze the excess liquid from the spinach beforehand. Blend the spinach for about 10 seconds.",
      " Scrape down the sides of the bowl and blend again for another 10 seconds. Leave the chopped spinach in the food processor.",
      " Heat a large skillet with 2 tablespoons of ghee or safflower oil over medium-high heat",
      "Add the diced onions and cook them for about 3 minutes, until they start to soften.",
      " Add the minced ginger, garlic, diced serrano pepper, and cumin seeds and cook for 30 seconds. Then, add the garam masala, turmeric, and cayenne pepper. Stir to coat the onions with the dried spices.",
      "Transfer the chopped spinach into the skillet. Next, add the heavy cream and salt. Cover the skillet with a lid and reduce the heat to medium. Let the spinach sauce simmer for about 5 minutes",
      " Uncover the lid and add the pan-fried paneer to the spinach sauce. Turn off the heat. Serve the palak paneer with basmati rice",
    ],
    image: palakpanner,
  },
];

export default recipes;
