import kaleporiyal from "../../img/kale/kaleporiyal.jpg";
import potatosabzi from "../../img/kale/kalepotatosabzi .jpg";
import kalechickpeas from "../../img/kale/kalechickpeas.jpg";
import kalecurry from "../../img/kale/kalecurry.jpg"
import kalesoup from "../../img/kale/kalesoup.jpg"
const recipes = [
  {
    id: 1,
    name: "Kale Poriyal",
    time: 15,
    servings: 2,
    ingredients: [
      "1 bunch Kale",
      "5 cloves Garlic",
      "1 medium Onion",
      "¼ tsp Mustard seeds",
      "½ tsp Broken Urad Dal",
      "¼ tsp Jeera",
      "2 Dry Red Chilli",
    ],
    steps: [
      "First, wash the kale nicely, remove the center spine, and chop up the leaves into small pieces",
      "Heat a large pan with oil and add the mustard seeds.",
      "Once it splutters, add the remaining ingredients given under to temper in the given order. Once the urad dal turns golden",
      "Heat a large pan with oil and add the mustard seeds. Once it splutters, add the remaining ingredients given under in the given order",
      "Once the urad dal turns golden, add the sliced garlic and saute for 30s",
      " Then add the chopped onion and continue to saute until the onions turn translucent.",
      " Add the salt now and continue to saute until the onions turns golden brown",
      "Now add the chopped kale and about ¼ Cup of water to the pan",
      "Continue to cook in medium flame, sautéing frequently, until all the water evaporates and the kale is cooked fully. Turn off the flame",
      "Serve hot",
    ],
    image: kaleporiyal,
    nutrients: [
      { name: "Calories", value: "115 kcal" },
      { name: "Protein", value: "3 g" },
      { name: "Fat", value: "5 g" },
      { name: "Carbs", value: "15 g" },
    ],
  },
  {
    id: 2,
    name: "Kale Potato Sabzi",
    time: 40,
    servings: 4,
    ingredients: [
      "4 cups Kale (Finely chopped)",
      "2 cups Potatoes (Boiled and Cubed)",
      "2 nos. Onions (Sliced)",
      "2 nos. Tomatoes (sliced)",
      "1 tsp Jeera or Cumin Seeds",
      "2 tsp Ginger Paste",
      "1 tsp Garlic Paste",
      "1 1/2 tsp Garam Masala Powder",
      "1 tsp Kashmiri Red chilli powder",
      "1/2 tsp Turmeric Powder or Haldi Powder",
      "1 tsp Jaggery",
    ],
    steps: [
      "Heat a pan, add oil, jeera, or cumin seeds and once they roast, add the sliced onions along with ginger paste and garlic paste",
      "Once the onions are slightly caramelized (not brown), add the sliced tomatoes",
      "Once the tomatoes have softened, add the spice powders - turmeric powder, red chili powder and salt to taste",
      "Saute this well",
      "Now add the finely chopped Kale",
      "The Kale will quickly wilt. Add some water and cook it along with the onion-tomato and spices mix",
      "Now add the boiled and cubed potatoes. Mix well.",
      "Add the garam masala powder and a tsp of jaggery powder",
      "Mix well, cover and cook on low heat for a couple of minutes",
      "Switch off the flame and serve with flatbreads or rice",
    ],
    image: potatosabzi,
    nutrients: [
      { name: "Calories", value: "250 kcal" },
      { name: "Protein", value: "5 g" },
      { name: "Fat", value: "14 g" },
      { name: "Carbs", value: "35 g" },
      { name: "Fiber", value: "7 g" },
      { name: "Sugar", value: "3 g" },
      { name: "Sodium", value: "300 mg" },
    ],
  },
  {
    id: 3,
    name: "Spiced Kale and ChickPeas",
    time: 25,
    servings: 4,
    ingredients: [
      "1 tablespoon extra-virgin olive oil",
      "3 cloves garlic, minced",
      "1-1 1/2 pounds kale, ribs removed",
      "1 cup reduced-sodium chicken broth",
      "1 teaspoon ground coriander",
      "½ teaspoon ground cumin",
      "1/4 teaspoon garam masala",
      "¼ teaspoon salt",
      "15-ounce can chickpeas, rinsed",
    ],
    steps: [
      "Heat oil in a Dutch oven over medium heat",
      "Add garlic and cook, stirring, until fragrant, about 30 seconds",
      "Add kale and cook, tossing with two large spoons, until bright green, about 1 minute",
      "Add broth, coriander, cumin, garam masala and salt",
      "Cover and cook, stirring occasionally, until the kale is tender, 8 to 10 minutes",
      "Stir in chickpeas ,cover and cook until the chickpeas are heated through, 1 to 2 minutes",
    ],
    image: kalechickpeas,
    nutrients: [
      { name: "Calories", value: "187 kcal" },
      { name: "Protein", value: "10 g" },
      { name: "Fat", value: "6 g" },
      { name: "Carbs", value: "28 g" },
    ],
  },
  {
    id: 4,
    name: "Kale Curry",
    time: 40,
    servings: 3,
    ingredients: [
        "Kale",
        "Coconut milk" ,
        "Spices like red chili powder and garam masala", 
        "turmeric powder and cumin powder",
        "Curry powder",
        "Onion",
        "Garlic cloves",
        "Tomato paste",
        "Potatoes and carrots"
    ],
    steps: [
        "Heat olive oil in a large pan over medium heat. 3 teaspoons olive oil",
        "Add chopped garlic and onions and cook for 3-4 minutes until lightly browned",
        "Add garlic cloves,1 onion",
        "Add tomato paste, cubed potatoes, carrots, and salt to the caramelized onions",
        "Cook for 7-8 minutes on low flame",
        "1 cup carrot,1 cup potatoes,1½ tablespoon tomato paste,salt to taste",
        "Add all the spices and mix to combine", 
        "Then add the chopped kale and stir ensuring it is all covered with the spices", 
        "Stir it for a couple of minutes",
        "Add ½ tablespoon curry powder,½ teaspoon red chili powder",
        "Add ¼ teaspoon turmeric powder,½ teaspoon garam masala,1 lb kale",
        "Add coconut milk and cook for 10-12 minutes on low flame(If required add water)",
        "Till the kale and potatoes are cooked",
         "Add some kasuri methi for the extra kick",
        "Serve Immediately"
    ],
    image: kalecurry,
    nutrients: [
      { name: "Calories", value: "332 kcal" },
      { name: "Protein", value: "7 g" },
      { name: "Fat", value: "28 g" },
      { name: "Carbs", value: "27 g" },
      {name :"Fiber",value : "8 g"},
      {name :"Sugar",value: "5 g"},
      {name : "Sodium",value : "152 mg"}
    ],
  },
  {
    id: 5,
    name: "Kale Soup",
    time: 20,
    servings: 4,
    ingredients: [
        "Kale",
        "Potatoes",
        "Garlic powder",
        "Onion",
        "Vegetable Stock/Broth",
        "Milk or Dairy-Free Milk",
        "Oil",
        "Black Pepper"
    ],
    steps: [
        "Heat the oil in a large saucepan and add the garlic, onion and potato", 
        "Cook for 5 minutes, stirring often, until soft",
        "Pour in the stock and simmer for 10 minutes",
        "Add the milk and kale and cook for 3 minutes or until the kale wilts slightly",
        "Season with pepper",
        "Use a handheld stick blender to puree the soup or transfer to a blender and whiz",
        "If your kale soup is too thick, stir in a little water and heat it up",
         "Serve with a drizzle of cream (or non-dairy cream) and a sprinkling of seeds"
    ],
    image: potatosabzi,
    nutrients: [
      { name: "Calories", value: "150 kcal" },
      { name: "Protein", value: "5 g" },
      { name: "Fat", value: "5 g" },
      { name: "Carbs", value: "21 g" },
      { name: "Fiber", value: "3 g" },
      { name: "Sugar", value: "5 g" },
      { name: "Sodium", value: "789 mg" },
    ],
  },
];

export default recipes;
